#!/bin/sh
# Generate SDL_wstiles_files.h embedding the browser client assets.
cd "$(dirname "$0")" || exit 1
FILES="data/index.html data/wstiles.js"
out=SDL_wstiles_files.h
echo "/* Generated by genfiles.sh - do not edit. */" > $out
count=1
for i in $FILES ; do
    echo "static const unsigned char WSTILES_file_${count}[] = {" >> $out
    perl -e 'local $/; my $d=<STDIN>; my @b=unpack("C*",$d); my @o;
             for my $i (0..$#b){ push @o, sprintf("0x%02x",$b[$i]); }
             for(my $i=0;$i<=$#o;$i+=16){ print "  ", join(", ", @o[$i..($i+15<=$#o?$i+15:$#o)]), ",\n"; }' < "$i" >> $out
    echo '};' >> $out
    echo >> $out
    count=$(expr $count + 1)
done
cat >> $out <<'EOF'
static const struct {
    const char *name;
    const char *mime;
    int length;
    const unsigned char *data;
} WSTILES_files[] = {
EOF
count=1
for i in $FILES ; do
    base=$(basename "$i")
    case "$base" in
        *.html) mime="text/html; charset=utf-8" ;;
        *.js)   mime="application/javascript" ;;
        *)      mime="application/octet-stream" ;;
    esac
    echo "    { \"$base\", \"$mime\", sizeof(WSTILES_file_${count}), WSTILES_file_${count} }," >> $out
    count=$(expr $count + 1)
done
echo '    { NULL, NULL, 0, NULL }' >> $out
echo '};' >> $out
exit 0
